### ISSUE TITLE
ValueError: could not convert string to float: 'mfit'

### ISSUE THREAD

**Issue by mzechmeister** [3fon3fonov/trifon#38]
When now starting from scratch and importing a *.rvc.dat file, I get:
```
Traceback (most recent call last):
  File "es_gui.py", line 2468, in showDialog_RV_input_file
    self.init_fit()            
  File "es_gui.py", line 2640, in init_fit
    fit.fitting(fileinput=False,outputfiles=[1,1,1], minimize_fortran=minimize_fortran,  fortran_kill=self.dyn_model_to_kill.value(), timeout_sec=self.master_timeout.value(), minimize_loglik=True,amoeba_starts=0, print_stat=False, eps=self.dyn_model_accuracy.value(), dt=self.time_step_model.value(), npoints=self.points_to_draw_model.value(), model_max= self.model_max_range.value(), model_min= self.model_min_range.value())
  File "./lib/RV_mod/__init__.py", line 3239, in fitting
    self.fit_results=fortranoutput.modfit(print_stat=print_stat)
  File "./lib/RV_mod/fortran_output.py", line 254, in modfit
    self.save_stat_array()
  File "./lib/RV_mod/fortran_output.py", line 213, in save_stat_array
    quad_trend  = float(self.best_par[i+4][0])
ValueError: could not convert string to float: 'mfit'
```

**Comment by 3fon3fonov** [comment]
OK ,i see it skip a line and instead to read the RV trend value it read the next line (too long for explanation). Can you please "git pull" to get the new version? Also can you please send me by e-mail that file to try to reproduce the error?

**Comment by mzechmeister** [comment]
Ok, re-running 
```bash installers/linux_OpenSuse_install.sh```
inparticular
```Installing the swift N-body lib, OK?  (you must, if you haven't done it already!)```
solves the issue (including ```gfortran: error: ./lib/libswift.a: No such file or directory```).
